### ISSUE TITLE
Share intent does not include any link to the app

### ISSUE THREAD

**Issue by kshia** [YaleSTC/YalePublic-android#142]
After clicking the info button in the action bar and clicking share, the email created via share intent doesn't include a link or even the name of the actual app.

![screenshot_20161216-163446](https://cloud.githubusercontent.com/assets/16885697/21279677/6b49ae64-c3af-11e6-8e34-24ff28831f96.png)

**Comment by stswidwinski** [comment]
Fixed. See screens below:

![Uploading device-2016-12-19-083918.png…]()
