### ISSUE TITLE
Events page text color and size

### ISSUE THREAD

**Issue by kshia** [YaleSTC/YalePublic-android#144]
Text color and size should be changed to match the rest of the app. Reduce text size and make grey on black (like the rest of the app) or black on grey (just to be more readable).

![screenshot_20161216-163521](https://cloud.githubusercontent.com/assets/16885697/21279738/d157dd84-c3af-11e6-9094-f1f9a1449efe.png)

**Comment by stswidwinski** [comment]
Fixed. See below.

![device-2016-12-19-084424](https://cloud.githubusercontent.com/assets/17051700/21314885/5ef37086-c5c7-11e6-948d-e17334f760fc.png)
