### ISSUE TITLE
"Open source license" activity title

### ISSUE THREAD

**Issue by kshia** [YaleSTC/YalePublic-android#146]
Change title in action bar of the activity displaying the list of open source licenses used. Currently says "Maps."

![screenshot_20161216-163913](https://cloud.githubusercontent.com/assets/16885697/21279809/3d3b1ec6-c3b0-11e6-827d-8f635fdfc094.png)

**Comment by stswidwinski** [comment]
Fixed.

![device-2016-12-19-082328](https://cloud.githubusercontent.com/assets/17051700/21314328/70d63232-c5c4-11e6-9c7d-85d374177657.png)
