### ISSUE TITLE
Unescape HTML characters in Events search

### ISSUE THREAD

**Issue by kshia** [YaleSTC/YalePublic-android#147]
Autocomplete/recommendations from Events search by name includes escaped HTML characters.

![screenshot_20161216-164133](https://cloud.githubusercontent.com/assets/16885697/21279869/95d2c99e-c3b0-11e6-8b21-cadb260efe10.png)

**Comment by stswidwinski** [comment]
Fixed! Please see below. Also all descriptions in the app are fixed too. 

![device-2016-12-19-093421](https://cloud.githubusercontent.com/assets/17051700/21316394/7c8e6856-c5ce-11e6-9efd-b40db23b4df7.png)
![device-2016-12-19-093439](https://cloud.githubusercontent.com/assets/17051700/21316374/6d37aa16-c5ce-11e6-8bbf-765ce6493a7a.png)
![device-2016-12-19-093453](https://cloud.githubusercontent.com/assets/17051700/21316373/6d37d9f0-c5ce-11e6-93a4-7acfa338da39.png)
