### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#26]
http://www.google.com/design/spec/material-design/introduction.html
https://developer.android.com/training/material/theme.html
https://developer.android.com/guide/topics/ui/themes.html
https://developer.android.com/training/material/compatibility.html
http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by krysjez** [comment]
Don't think this will be happening for a while. If we do a visual redesign might as well do a full UX redesign as well. Let's see what OPAC says after the next delivery.

**Comment by jasonkliu** [comment]
@krysjez I already changed the theme and merged it - it looks better this way.
One thing they specifically didn't like was the "holo" theme for the title bar.

**Comment by jasonkliu** [comment]
Need to change colors of title bar

**Comment by krysjez** [comment]
![material_spec](https://cloud.githubusercontent.com/assets/4814522/5807128/1f771152-9fee-11e4-8de1-2fe77af751c1.png)
