### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#33]
- [x] Look at gradle output for lint issues: `build/outputs/lint-results*`
- [x] Add quoted strings "foobar" into `res/values/strings.xml` then use `@string/foobar`
- [x] Fix possible spacing issues (4 each, especially for multiline statements)
- [x] Fix brace issues with spacing
- [x] Issue #15
- [x] Documentation on #31
- [x] Rename `news` folder to `News` with same syntax as other folders

Google's Java Style guide - https://google-styleguide.googlecode.com/svn/trunk/javaguide.html
The official style guide - https://source.android.com/source/code-style.html
An informative powerpoint - http://courses.coreservlets.com/Course-Materials/pdf/android/Android-Coding-Style.pdf

**Comment by Ebstein** [comment]
No clear guidance for .xml files. 

1.Unified those so that we are consistent with the earliest files. 
2.Added comments to .xml files connected to events. 
3.refactored the names of few .xml files. 
4.Deleted unused .xml files.

**Comment by Ebstein** [comment]
The activity_*.xml files have to be looked at and probably deleted. Those are all almost the same and can be just deleted as the content is set programatically and we only need one such file to inflate in all classes.

**Comment by Ebstein** [comment]
Refactor the events to centralize checking if data is cached or at least move that to the adapter.

**Comment by jasonkliu** [comment]
Explanation of Locale bug:  e3dfccccd623878ebf1fa1e962422ae822e618b6

Calling String#toLowerCase() or #toUpperCase() without specifying an explicit locale is a common source of bugs. The reason for that is that those methods will use the current locale on the user's device, and even though the code appears to work correctly when you are developing the app, it will fail in some locales. For example, in the Turkish locale, the uppercase replacement for i is not I.

If you want the methods to just perform ASCII replacement, for example to convert an enum name, call String#toUpperCase(Locale.US) instead. If you really want to use the current locale, call String#toUpperCase(Locale.getDefault()) instead.

More info: http://developer.android.com/reference/java/util/Locale.html#default_locale

To suppress this error, use the issue id "DefaultLocale" as explained in the Suppressing Warnings and Errors section.
