### ISSUE TITLE
Unification of progress dialogs

### ISSUE THREAD

**Issue by Ebstein** [YaleSTC/YalePublic-android#37]
The progress dialogs in photos, events and videos are different. Decide on the format of the progress dialogs and remake the ones that do not fit the style.

**Comment by jasonkliu** [comment]
Ditto: This is not (currently) an issue as it is being replaced in #43.

**Comment by Ebstein** [comment]
Done?

**Comment by jasonkliu** [comment]
if (photos is done)
    then done();
else
    !done();
endif

**Comment by mahirrana** [comment]
This is done in commit 61e53b7b8dd4f4f04b75aee3084daeeee9c7f82d

**Comment by mahirrana** [comment]
The video progress dialog needs to be changed to look like events and photos
