### ISSUE TITLE
Events Feature - List View

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#44]
Events should show the upcoming 6 months and no past events.
By default, a list view should be shown of the current events as well as the current calendar tab.
Events should be searchable.

**Comment by Ebstein** [comment]
Events are not searchable at the moment. The list only shows events for the current event (just as in current application). There is no point in making a list for more than a month. It is long enough as it is (~200 elements per month). 

TODO:
Scroll the list to current day.

**Comment by Ebstein** [comment]
Done. Look at the pull req

**Comment by jasonkliu** [comment]
#102 finishes this.
