### ISSUE TITLE
Changing link & icon

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#46]
The bottom right icon is currently for the Arts Calendar, but should be switchable to the following:
(rotates: commencement, AYA weekend, and orientation - link to app) 

Possibly through changeable `goo.gl` link, but maybe just need to deploy new version of the app.

**Comment by jasonkliu** [comment]
https://yalestc.github.io/YalePublic-android/

**Comment by clhpeterson** [comment]
https://yalestc.github.io/YalePublic-android/index.json

**Comment by jasonkliu** [comment]
#103
