### ISSUE TITLE
Change displayed names of activities

### ISSUE THREAD

**Issue by Ebstein** [YaleSTC/YalePublic-android#50]
Change the displayed names of activities on the action bar of the application. This would also involve adding the Yale logo in place of the android placeholder.

**Comment by jasonkliu** [comment]
@Ebstein Since I merged in the new theme, the current app logo doesn't show up in the top left (Android placeholder) position anymore. This will also have to be changed.

**Comment by jasonkliu** [comment]
To be fair the original app does not show the application logo in the top left. 

I have to code in each place where we want the logo to show up, in progress...

**Comment by jasonkliu** [comment]
The logo is only displayed on the home screen - otherwise it is too messy elsewhere. 
A back arrow goes up on level of the application (depicted in AndroidManifest.xml)
