### ISSUE TITLE
New header style everywhere

### ISSUE THREAD

**Issue by krysjez** [YaleSTC/YalePublic-android#72]
See issue "material design" for hex codes and general idea of how it looks

It primarily involves changing the color of the background and text of the header. And making the header text meaningful and properly punctuated with spaces.

Changing status bar color is optional.

**Comment by jasonkliu** [comment]
I believe we already did this? You mean the one from #26?
By header, you mean the "Yale University part", and the "status bar" means the one with color 164579, correct?

**Comment by krysjez** [comment]
Has it been changed across all the screens? I was under the impression from screenshots posted in #71 that everything else was still using the bright blue header.

Yes and yes, #26, sorry was on my phone and couldn't figure out how to link issues.

**Comment by jasonkliu** [comment]
@krysjez It has been changed across all the screens. If you look at the [branches page](https://github.com/YaleSTC/YalePublic-android/branches), the `listView` branch is 8 commits behind and 24 commits ahead of master.  The 8 commits that were merged into master contain the fixes for the header; however, the branch point for the `listView` branch was done before the changes were merged into master.

**Comment by krysjez** [comment]
Ooh okay got it. Thanks.
