### ISSUE TITLE
Auth: Bug: Fix Maven build for jInstagram on android studio

### ISSUE THREAD

**Issue by abchandra** [YaleSTC/YalePublic-android#74]

**Comment by abchandra** [comment]
Fixed, committed to InstagramPhotos branch

**Comment by jasonkliu** [comment]
@abchandra please push :ocean:

**Comment by abchandra** [comment]
Sorry, pushed. Don't worry about it until we merge though - the fix I have has explicit excludes on certain files, and I may find another way to do it.
