### ISSUE TITLE
Add Instagram keys to install-dummykeys.sh

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#81]
Otherwise, Travis build fails.

**Comment by jasonkliu** [comment]
See 2f0398b684db0fc9f8c5aa536fa2f137c6c08ffa

**Comment by jasonkliu** [comment]
@abchandra The automatic build system requires the Instagram keys to be added to the repo, which I did in the commit above.  Please pull this before making any changes.

If you have some work you haven't committed yet:
```sh
$ git stash
$ git pull
$ git stash apply
```

**Comment by abchandra** [comment]
Done, thanks :)

**Comment by jasonkliu** [comment]
For some reason, the commit never made it on. I reapplied with `git cherry-pick`, try pulling again.
